module.exports = {
	'en': {
		'Þjóðsagnasafn': 'Folklore collection',
		'Efnisorð': 'Topic words',
		'Velja efnisorð': 'Select topic words',
		'Leit að efnisorði': 'Search',
		'Hreinsa val': 'Clear selection',
		'Leit í heiti eða efni': 'Search for title or summary',
		'Handrit': 'Manuscript',
		'Tenging við einstakling': 'Relation to person',
		'Heimildamaður': 'Informant',
		'Skrásetjari': 'Scribe',
		'Sýsla': 'County of',
		'einstaklings': 'person',
		'Útlönd': 'Foreign',
		'Undraland': 'Mythical',
		'Hreppur': 'Municipality of',
		'Kyn': 'Gender of',
		'Karl': 'Male',
		'Kona': 'Female',
		'Leita': 'Search',
		'Sögustaðir': 'Places in legends',
		'Efnisorð': 'Topic words',
		'Þjóðsagnasöfn': 'Folklore collections',
		'Sæki gögn fyrir kort': 'Fetching data for the map',
		'Flóknari fyrirspurnir geta tekið ofurlitla stund að birtast': 'Complex queries might takes a little while',
		'Nafn': 'Name',
		'Heimild': 'Reference',
		'': '',
	}
};